### ISSUE TITLE
Not able to execute Terraform Plan in Jenkins

### ISSUE THREAD

**Issue by anujagnivanshi** [alexandarp/gitops-terraform-jenkins#10]
Hey Alex ! Need Your Help in this. The terraform plan command working fine in my local machine but throwing error ( mention below ) while running in jenkins pipeline. although terraform version is same everywhere.

error :

Error: Error fetching Availability Zones: UnauthorizedOperation: You are not authorized to perform this operation.
	status code: 403, request id: 31bb0a5f-14b9-4f16-827b-74b771a8c271

I am using data "aws_availability_zones" module to fetch az for subnet.

**Comment by alexandarp** [comment]
You need to add your AWS credentials to Jenkins.

**Comment by alexandarp** [comment]
If you continue to have issues, please open another issue.
