### ISSUE TITLE
Terraform init not wokring

### ISSUE THREAD

**Issue by DhruvinSoni30** [alexandarp/gitops-terraform-jenkins#13]
While running Jenkins job I got below error:-

terraform: command not found

Jenkins successfully fetch the git repository but when moving to next step (init) terraform init not working.

The command is also not working in the backend it gave me below error:-

Error installing provider "aws": mkdir .terraform: permission denied.

```
Terraform analyses the configuration and state and automatically downloads
plugins for the providers used. However, when attempting to download this
plugin an unexpected error occurred.

This may be caused if for some reason Terraform is unable to reach the
plugin repository. The repository may be unreachable if access is blocked
by a firewall.

If automatic installation is not possible or desirable in your environment,
you may alternatively manually install plugins by downloading a suitable
distribution package and placing the plugin's executable file in the
following directory:
    terraform.d/plugins/linux_amd64


Error: mkdir .terraform: permission denied
```

I have already installed terraform and also set it's path in .bash_profile, also installed terraform plugin.

**Comment by alexandarp** [comment]
You should check your permissions, this seems to be related to the folder you're running Terraform in.

**Comment by DhruvinSoni30** [comment]
What should be the permission of terraform? I have changed it from root to jenkins but still got the same error.

**Comment by alexandarp** [comment]
The user executing the Terraform binary should have permission to create files in the directory its running Terraform in.

**Comment by alexandarp** [comment]
If you continue to have issues, please open another issue.
