### ISSUE TITLE
Facing the command not found error 

### ISSUE THREAD

**Issue by veeranji23** [alexandarp/gitops-terraform-jenkins#8]
Hello Alex,

when i am building the job facing the below error .Please help me on this .

Started by user admin
11:53:19 Connecting to https://api.github.com using GITHUB/******
Obtained Jenkinsfile from 322b4fa1334814f374f557fcfa06fc52e5d4ad60
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] Start of Pipeline
[Pipeline] stage
[Pipeline] { (checkout)
[Pipeline] node
Running on Jenkins in /var/lib/jenkins/workspace/TFAutomation_master
[Pipeline] {
[Pipeline] cleanWs
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Deferred wipeout is used...
[WS-CLEANUP] done
[Pipeline] checkout
using credential 5c6d0070-f373-4088-a65b-d23a17fd80e1
Cloning the remote Git repository
Cloning with configured refspecs honoured and without tags
Cloning repository https://github.com/veeranji23/TFAutomation.git
 > git init /var/lib/jenkins/workspace/TFAutomation_master # timeout=10
Fetching upstream changes from https://github.com/veeranji23/TFAutomation.git
 > git --version # timeout=10
using GIT_ASKPASS to set credentials 
 > git fetch --no-tags --progress -- https://github.com/veeranji23/TFAutomation.git +refs/heads/master:refs/remotes/origin/master # timeout=10
 > git config remote.origin.url https://github.com/veeranji23/TFAutomation.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/master:refs/remotes/origin/master # timeout=10
 > git config remote.origin.url https://github.com/veeranji23/TFAutomation.git # timeout=10
Fetching without tags
Fetching upstream changes from https://github.com/veeranji23/TFAutomation.git
using GIT_ASKPASS to set credentials 
 > git fetch --no-tags --progress -- https://github.com/veeranji23/TFAutomation.git +refs/heads/master:refs/remotes/origin/master # timeout=10
Checking out Revision 322b4fa1334814f374f557fcfa06fc52e5d4ad60 (master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 322b4fa1334814f374f557fcfa06fc52e5d4ad60 # timeout=10
Commit message: "revertback"
 > git rev-list --no-walk 0530c657b60b125b6fe5eb197c5468770dc8373c # timeout=10
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (init)
[Pipeline] node
Running on Jenkins in /var/lib/jenkins/workspace/TFAutomation_master
[Pipeline] {
[Pipeline] withCredentials
Masking supported pattern matches of $AWS_ACCESS_KEY_ID or $AWS_SECRET_ACCESS_KEY
[Pipeline] {
[Pipeline] ansiColor
[Pipeline] {
[Pipeline] sh
+ terraform init
/var/lib/jenkins/workspace/TFAutomation_master@tmp/durable-8af3b398/script.sh: line 1: terraform: command not found
[Pipeline] }
[Pipeline] // ansiColor
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

ERROR: script returned exit code 127
Finished: FAILURE

**Comment by alexandarp** [comment]
Did you install Terraform?

If you did, is it part of your path?

**Comment by alexandarp** [comment]
If you continue to have issues, please open another issue.
